$(function(){
	$(addMember).on("click",function(){
		$.ajax({
			url:"member",
			type:"post",
			dataType:"json",
			data:{
				mid:1000,
				name:"史密斯",
				salary:9999.12,
				hiredate:"2019-01-17"
			},
			success:function(data){
				$(showDiv).append("<p>增加处理结果:"+data.flag+"</P");
			},
			error:function(data){
				$(showDiv).append("<h2>sorry,出错了!</h2>");
			}
		});
	});
	
	$(editMember).on("click",function(){
		$.ajax({
			url:"member?mid=10001&name=西蒙斯大帝&salary=9998.0&hiredate=2019-02-01",
			type:"put",
			dataType:"json",
			success:function(data){
				$(showDiv).append("<p>修改处理结果:"+data.flag+"</P");
			},
			error:function(data){
				$(showDiv).append("<h2>sorry,出错了!</h2>");
			}
		});
	});
	$(removeMember).on("click",function(){
		$.ajax({
			url:"member/10001",
			type:"delete",
			dataType:"json",
			success:function(data){
				$(showDiv).append("<p>删除处理结果:"+data.flag+"</P");
			},
			error:function(data){
				$(showDiv).append("<h2>sorry,出错了!</h2>");
			}
		});
	});
})